// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VasuthalozatPublicApplication.Entities;

namespace VasuthalozatPublicApplication.Migrations
{
    [DbContext(typeof(VasutContext))]
    [Migration("20220126221819_DataSeed")]
    partial class DataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("VasuthalozatPublicApplication.Entities.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("ID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Wonoharjo"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Miaoyu"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Chivhu"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Beni"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Manicaragua"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Bentar"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Golcuv Jeníkov"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Kuantan"
                        },
                        new
                        {
                            ID = 9,
                            Name = "Nova Kakhovka"
                        },
                        new
                        {
                            ID = 10,
                            Name = "Dollard-Des Ormeaux"
                        },
                        new
                        {
                            ID = 11,
                            Name = "Kabardinka"
                        },
                        new
                        {
                            ID = 12,
                            Name = "Caoxi"
                        },
                        new
                        {
                            ID = 13,
                            Name = "San Lorenzo"
                        },
                        new
                        {
                            ID = 14,
                            Name = "Normanton"
                        },
                        new
                        {
                            ID = 15,
                            Name = "Sao Joao del Rei"
                        },
                        new
                        {
                            ID = 16,
                            Name = "Dongshi"
                        },
                        new
                        {
                            ID = 17,
                            Name = "Arruda dos Vinhos"
                        },
                        new
                        {
                            ID = 18,
                            Name = "Elliot"
                        },
                        new
                        {
                            ID = 19,
                            Name = "Upper San Mateo"
                        },
                        new
                        {
                            ID = 20,
                            Name = "Kalilangan"
                        });
                });

            modelBuilder.Entity("VasuthalozatPublicApplication.Entities.Railway", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("FromID")
                        .HasColumnType("int");

                    b.Property<int>("Km")
                        .HasColumnType("int");

                    b.Property<int?>("ToID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FromID");

                    b.HasIndex("ToID");

                    b.ToTable("Railways");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Km = 38
                        },
                        new
                        {
                            ID = 2,
                            Km = 56
                        },
                        new
                        {
                            ID = 3,
                            Km = 83
                        },
                        new
                        {
                            ID = 4,
                            Km = 145
                        },
                        new
                        {
                            ID = 5,
                            Km = 49
                        },
                        new
                        {
                            ID = 6,
                            Km = 82
                        },
                        new
                        {
                            ID = 7,
                            Km = 92
                        },
                        new
                        {
                            ID = 8,
                            Km = 95
                        },
                        new
                        {
                            ID = 9,
                            Km = 42
                        },
                        new
                        {
                            ID = 10,
                            Km = 49
                        },
                        new
                        {
                            ID = 11,
                            Km = 66
                        },
                        new
                        {
                            ID = 12,
                            Km = 34
                        },
                        new
                        {
                            ID = 13,
                            Km = 1
                        },
                        new
                        {
                            ID = 14,
                            Km = 67
                        },
                        new
                        {
                            ID = 15,
                            Km = 14
                        },
                        new
                        {
                            ID = 16,
                            Km = 38
                        },
                        new
                        {
                            ID = 17,
                            Km = 66
                        },
                        new
                        {
                            ID = 18,
                            Km = 116
                        },
                        new
                        {
                            ID = 19,
                            Km = 75
                        },
                        new
                        {
                            ID = 20,
                            Km = 82
                        },
                        new
                        {
                            ID = 21,
                            Km = 134
                        },
                        new
                        {
                            ID = 22,
                            Km = 68
                        },
                        new
                        {
                            ID = 23,
                            Km = 148
                        },
                        new
                        {
                            ID = 24,
                            Km = 2
                        },
                        new
                        {
                            ID = 25,
                            Km = 92
                        },
                        new
                        {
                            ID = 26,
                            Km = 116
                        },
                        new
                        {
                            ID = 27,
                            Km = 98
                        },
                        new
                        {
                            ID = 28,
                            Km = 56
                        },
                        new
                        {
                            ID = 29,
                            Km = 49
                        },
                        new
                        {
                            ID = 30,
                            Km = 34
                        },
                        new
                        {
                            ID = 31,
                            Km = 45
                        },
                        new
                        {
                            ID = 32,
                            Km = 131
                        },
                        new
                        {
                            ID = 33,
                            Km = 95
                        },
                        new
                        {
                            ID = 34,
                            Km = 134
                        },
                        new
                        {
                            ID = 35,
                            Km = 98
                        },
                        new
                        {
                            ID = 36,
                            Km = 89
                        },
                        new
                        {
                            ID = 37,
                            Km = 78
                        },
                        new
                        {
                            ID = 38,
                            Km = 75
                        },
                        new
                        {
                            ID = 39,
                            Km = 68
                        },
                        new
                        {
                            ID = 40,
                            Km = 89
                        },
                        new
                        {
                            ID = 41,
                            Km = 117
                        },
                        new
                        {
                            ID = 42,
                            Km = 96
                        },
                        new
                        {
                            ID = 43,
                            Km = 46
                        },
                        new
                        {
                            ID = 44,
                            Km = 148
                        },
                        new
                        {
                            ID = 45,
                            Km = 117
                        },
                        new
                        {
                            ID = 46,
                            Km = 130
                        },
                        new
                        {
                            ID = 47,
                            Km = 115
                        },
                        new
                        {
                            ID = 48,
                            Km = 148
                        },
                        new
                        {
                            ID = 49,
                            Km = 56
                        },
                        new
                        {
                            ID = 50,
                            Km = 11
                        },
                        new
                        {
                            ID = 51,
                            Km = 47
                        },
                        new
                        {
                            ID = 52,
                            Km = 112
                        },
                        new
                        {
                            ID = 53,
                            Km = 56
                        },
                        new
                        {
                            ID = 54,
                            Km = 96
                        },
                        new
                        {
                            ID = 55,
                            Km = 2
                        },
                        new
                        {
                            ID = 56,
                            Km = 55
                        },
                        new
                        {
                            ID = 57,
                            Km = 1
                        },
                        new
                        {
                            ID = 58,
                            Km = 11
                        },
                        new
                        {
                            ID = 59,
                            Km = 2
                        },
                        new
                        {
                            ID = 60,
                            Km = 129
                        },
                        new
                        {
                            ID = 61,
                            Km = 46
                        },
                        new
                        {
                            ID = 62,
                            Km = 83
                        },
                        new
                        {
                            ID = 63,
                            Km = 129
                        },
                        new
                        {
                            ID = 64,
                            Km = 115
                        },
                        new
                        {
                            ID = 65,
                            Km = 49
                        },
                        new
                        {
                            ID = 66,
                            Km = 78
                        },
                        new
                        {
                            ID = 67,
                            Km = 46
                        },
                        new
                        {
                            ID = 68,
                            Km = 55
                        },
                        new
                        {
                            ID = 69,
                            Km = 46
                        },
                        new
                        {
                            ID = 70,
                            Km = 132
                        },
                        new
                        {
                            ID = 71,
                            Km = 115
                        },
                        new
                        {
                            ID = 72,
                            Km = 75
                        },
                        new
                        {
                            ID = 73,
                            Km = 130
                        },
                        new
                        {
                            ID = 74,
                            Km = 112
                        },
                        new
                        {
                            ID = 75,
                            Km = 132
                        },
                        new
                        {
                            ID = 76,
                            Km = 145
                        },
                        new
                        {
                            ID = 77,
                            Km = 45
                        },
                        new
                        {
                            ID = 78,
                            Km = 75
                        },
                        new
                        {
                            ID = 79,
                            Km = 115
                        },
                        new
                        {
                            ID = 80,
                            Km = 115
                        },
                        new
                        {
                            ID = 81,
                            Km = 42
                        },
                        new
                        {
                            ID = 82,
                            Km = 67
                        },
                        new
                        {
                            ID = 83,
                            Km = 99
                        },
                        new
                        {
                            ID = 84,
                            Km = 14
                        },
                        new
                        {
                            ID = 85,
                            Km = 2
                        },
                        new
                        {
                            ID = 86,
                            Km = 131
                        },
                        new
                        {
                            ID = 87,
                            Km = 148
                        },
                        new
                        {
                            ID = 88,
                            Km = 47
                        },
                        new
                        {
                            ID = 89,
                            Km = 115
                        },
                        new
                        {
                            ID = 90,
                            Km = 99
                        });
                });

            modelBuilder.Entity("VasuthalozatPublicApplication.Entities.Railway", b =>
                {
                    b.HasOne("VasuthalozatPublicApplication.Entities.City", "From")
                        .WithMany()
                        .HasForeignKey("FromID");

                    b.HasOne("VasuthalozatPublicApplication.Entities.City", "To")
                        .WithMany()
                        .HasForeignKey("ToID");

                    b.Navigation("From");

                    b.Navigation("To");
                });
#pragma warning restore 612, 618
        }
    }
}
